
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ciao
      MYSQL_DATABASE: hw1
      MYSQL_USER: pippo
      MYSQL_PASSWORD: ciao
    volumes:
      - mysql_data:/var/lib/mysql  
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - my_network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server 
    ports:
      - 50051:50051 #mappo solo la porta del server per accedere al servizio esternamente
    depends_on:
      - mysql
    networks:
      - my_network  
  
  datacollector:
    build:
      context: .
      dockerfile: Dockerfile.datacollector
    container_name: data_collector
    depends_on:
      - mysql
    networks:
      - my_network  
    restart: always        

networks:
  my_network:
    driver: bridge

volumes:
    mysql_data:
